// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahwkdhxgjthgqgwrlmtd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFod2tkaHhnanRoZ3Fnd3JsbXRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzI5OTAsImV4cCI6MjA2NDcwODk5MH0._NPpQqR-LeqjLQWDssUE0ilydcRD6_rUrSQhnwXexZk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);